import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import SettingsProvider from "@/context/SettingsContext";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SettingsProvider>
        <body className={outfit.className}>{children}</body>
      </SettingsProvider>
    </html>
  );
}
